---
name: 'Publish latest release to Ansible Galaxy'

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  build:
    name: 'Publish to Ansible Galaxy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout'
        uses: 'actions/checkout@v2'
      - name: 'galaxy'
        uses: 'robertdebock/galaxy-action@1.2.0'
        with:
          galaxy_api_key: '${{ secrets.galaxy_api_key }}'
          git_branch: 'main'
